exports.METROS = [
    {metro: "Napa", state: "CA"},
    {metro: "Phoenix Lake", state: "CA"},
    {metro: "Madera", state: "CA"},
    {metro: "Santa Rosa", state: "CA"},
    {metro: "San Francisco", state: "CA"},
    {metro: "Riverside", state: "CA"},
    {metro: "Pahrump", state: "CA"},
    {metro: "Sacramento", state: "CA"},
    {metro: "San Diego", state: "CA"},
    {metro: "San Luis Obispo", state: "CA"},
    {metro: "Santa Cruz", state: "CA"},
    {metro: "Los Angeles", state: "CA"},
    {metro: "Ukiah", state: "CA"},
    {metro: "Crescent City", state: "CA"},
    {metro: "Bakersfield", state: "CA"},
    {metro: "Vallejo", state: "CA"},
    {metro: "Clearlake", state: "CA"},
    {metro: "Susanville", state: "CA"},
    {metro: "Hanford", state: "CA"},
    {metro: "San Jose", state: "CA"},
    {metro: "Yuba City", state: "CA"},
    {metro: "Eureka", state: "CA"},
    {metro: "Ventura", state: "CA"},
    {metro: "Redding", state: "CA"},
    {metro: "Chico", state: "CA"},
    {metro: "Truckee", state: "CA"},
    {metro: "Red Bluff", state: "CA"},
    {metro: "Stockton", state: "CA"},
    {metro: "Fresno", state: "CA"},
    {metro: "Merced", state: "CA"},
    {metro: "Reno", state: "CA"},
    {metro: "Santa Barbara", state: "CA"},
    {metro: "Visalia", state: "CA"},
    {metro: "Salinas", state: "CA"},
    {metro: "Las Vegas", state: "CA"},
    {metro: "Modesto", state: "CA"},
    {metro: "El Centro", state: "CA"},
    {metro: "Bishop", state: "CA"}
];
